`Promise` <sub>(객체)</sub> 에러 처리
====

##### `Promise` <sub>(객체)</sub> 거부 시 제어 흐름 이동
- 거부 처리 핸들러 → 최근접 에러 처리 핸들러
  - 체이닝 시 에러 처리 용이

##### `catch` 핸들러
- 모든 이전 `Promise` <sub>(객체)</sub> 거부 <sub>(에러)</sub> 처리
  - 체인 끝 위치 권장
- 동작 정상 수행 시 실행 X
- 문제 발생 시 실행
  - 네트워크 이상
  - 부적절한 JSON 형식
  - 기타 등등

##### `fetch` <sub>(메서드)</sub> → 부재 url 전달
```javascript
fetch('https://no-such-server') // 거부 발생
  .then(response => response.json())

  // 이전 핸들러 내 에러 (Promise 객체 거부) 처리
  .catch(alert);
```

##### 응답 내 부적절한 JSON 형식 에러 처리
```javascript
fetch('/article/promise-chaining/user.json')
  .then(response => response.json())
  .then(user => fetch(`https://api.github.com/users/${user.name}`))
  .then(response => response.json())
  .then(githubUser => new Promise((resolve, reject) => {
    let img = document.createElement('img');
    img.src = githubUser.avatar_url;
    img.className = "promise-avatar-example";

    document.body.append(img);

    setTimeout(() => {
      img.remove();

      resolve(githubUser);
    }, 3000);
  }))

  // 이전 핸들러 내 에러 (Promise 객체 거부) 처리
  .catch(e => (e.message);
```

### 암시적 `try…catch`

##### `Promise` <sub>(객체)</sub> · 핸들러 내 코드 대상 적용
- 에러 시 거부 처리 <sub>(에러 → 거부)</sub>
  - 에러 == 거부된 `Promise` <sub>(객체)</sub>
```javascript
new Promise((resolve, reject) => {
  throw new Error("에러");
}).catch(alert); // Error: 에러

↓↓↓

new Promise((resolve, reject) => {
  reject(new Error("에러"));
}).catch(alert); // Error: 에러
```

##### 핸들러 내 에러 시 제어 흐름 이동
- 에러 <sub>(거부)</sub> 핸들러 → 최근접 에러 처리 핸들러
```javascript
new Promise((resolve, reject) => {
  resolve("OK");
}).then((result) => {

  // Promise (객체) 거부
  throw  new Error("에러");
//reject(new Error("에러"));

// 이전 핸들러 내 에러 (Promise 객체 거부) 처리
}).catch(alert); // Error: 에러
```

##### 모든 에러 유형 처리 <sub>(`throw` 문 외)</sub>
```javascript
new Promise((resolve, reject) => {
  resolve("OK");
}).then((result) => {
  blabla();// 부재 함수 호출
//reject(new ReferenceError(…));

// 이전 핸들러 내 ReferenceError (Promise 객체 거부) 처리
}).catch(alert); // ReferenceError: blabla is not defined
```

##### `catch` 핸들러 처리 대상
- 명시적인 거부
- 이전 핸들러 내 비정상 에러 <sub>(에러 → 거부)</sub>

### 다시 던지기

#### `catch` 핸들러

##### `try…catch` 유사 역할 수행
- 다수 이전 `then` 핸들러 내 모든 에러 처리
- 에러 분석 후 처리 불가능 에러 다시 던지기

##### 제어 흐름 이동
- 에러 처리 성공 → 최근접 `then` 핸들러
  - 동작 속행
```javascript
/* 실행 순서
 ① Promise (객체)
 ② catch 핸들러
 ③ then 핸들러
 */

// ①
new Promise((resolve, reject) => {
  throw  new Error("에러");
//reject(new Error("에러"));

// ②
}).catch(function(e) {
  `${e} 처리 완료 · 동작 속행`;

// ③
}).then(() => "다음 핸들러 동작");
```
- `throw` <sub>(문)</sub> 사용 → 최근접 에러 처리 핸들러
  - 에러 다시 던지기
```javascript
/* 실행 순서
 ① Promise (객체)
 ② catch 핸들러 (1번째)
 ③ catch 핸들러 (2번째)
 */

// ①
new Promise((resolve, reject) => {
  throw  new Error("에러");
//reject(new Error("에러"));

// ②
}).catch(function(e) {
  if (e instanceof URIError) {
    …처리 가능 에러 처리…

  // Error ≠ URIError
  } else {
    throw e; // 처리 불가능 에러 다시 던지기
  }

// 핸들러 미실행
}).then(function() {
  …

// ③
}).catch(e => {
  `알 수 없는 에러 발생: ${e}`;
  // 반환 값 無 → 동작 속행
});
```

### 미처리 거부

##### 미처리 에러 <sub>(거부)</sub> → 전역 에러 생성
- 체인 끝 `catch` 핸들러 無
- `catch` 핸들러 내 에러 처리 X
- 기타 등등
```javascript
new Promise(function() {
  noSuchFunction(); // 부재 함수 호출 (에러)
//reject(…);
}).then(() => {
  …이행된 Promise (객체) 처리…
}); // 체인 끝 catch 핸들러 無
    // - 전역 에러 생성
```

##### [`unhandledrejection`](https://html.spec.whatwg.org/multipage/webappapis.html#unhandled-promise-rejections) <sub>(브라우저 표준 이벤트)</sub>
- 전역 에러 시 발생 <sub>(보통 회복 불가능)</sub>
  - 최선 대안 수행
    - 사용자 알림
    - 에러 정보 서버 전송
- 이벤트 객체 내 에러 정보 저장 <sub>(특수 프로퍼티)</sub>
  - 에러 처리 시 이용

|프로퍼티|값|
|:---:|---|
|`promise`|거부된 `Promise` <sub>(에러 유발 객체)</sub>|
|`reason`|미처리 에러 객체|

```javascript
window.addEventListener('unhandledrejection', function(event) {
  event.promise; // "[object Promise]"
  event.reason;  // Error: 에러
});

new Promise(function() {
  throw  new Error("에러");
  reject(new Error("에러"));
}); // 체인 끝 catch 핸들러 無
    // - 전역 에러 생성
```

<br />

요약
====

#### `catch` <sub>(핸들러)</sub>

##### `Promise` <sub>(객체)</sub> 내 모든 에러 <sub>(거부)</sub> 처리
- a. `reject(…)` 호출 <sub>(명시적 거부)</sub>
- b. 에러 던지기 <sub>(암시적 거부)</sub>

##### 모든 이전 핸들러 내 모든 에러 처리
- 에러 분석 후 처리 <sub>(커스텀 에러 클래스 유용)</sub>
- 처리 불가능 에러 <sub>(보통 실수)</sub> 다시 던지기
- 회복 방법 부재 시 미사용 가능

##### `unhandledrejection` <sub>(브라우저 이벤트)</sub> 핸들러
- 미처리 <sub>(전역)</sub> 에러 처리 <sub>(보통 회복 불가능)</sub>
  - 에러 추적 후 사용자 · 서버 알림

<br />

## <img src="../../images/commons/icons/circle-check-solid.svg" /> 과제

### `setTimeout` <sub>(메서드)</sub> 내 에러

##### `catch` 핸들러 트리거 여부 · 이유
```javascript
new Promise(function(resolve, reject) {
  setTimeout(() => {
    throw new Error("에러");
  }, 1000);
}).catch(alert);
```

<br />

<img src="../../images/commons/icons/circle-answer.svg" />

#### `catch` 핸들러 실행 X

##### 암시적 `try…catch`
- `Promise` <sub>(객체)</sub> · 핸들러 내 동기적 에러 처리
  - 에러 → 거부 <sub>(변환)</sub>

##### `setTimeout` <sub>(메서드)</sub> 내 에러 시점
- executor 실행 중 X
- 나중
  - `Promise` <sub>(객체)</sub> : 에러 처리 X
